[package]
name = "keys"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"
description = "Secp256k1 crypto for Eos"

[dependencies]
bitcoin_hashes = "0.7"
byteorder = "1.2"
rust-crypto = "0.2.36"
rustc-hex = "2"

[dependencies.rand]
version = "0.6"
features = ["i128_support"]

[dependencies.secp256k1]
version = "0.15"
features = ["std", "recovery"]

[dev-dependencies]
hex = "=0.3.2"
